Configurações As screen:
    Fill: =RGBA(32, 32, 32, 1)
    LoadingSpinnerColor: =RGBA(100, 118, 132, 1)

    Button2_29 As button:
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(43, 43, 43, 1)
        FontWeight: =FontWeight.Semibold
        Height: =261
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(100, 118, 132, 1), -20%)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =24
        Text: =""
        Width: =640
        ZIndex: =1

    Image4_2 As image:
        BorderColor: =RGBA(197, 203, 207, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        Height: =91
        Image: =First(LookUp(Cadastro_Usuario,Email = VarDadosUsuario.Email).Anexos).Value
        ImagePosition: =ImagePosition.Fill
        RadiusBottomLeft: =60
        RadiusBottomRight: =60
        RadiusTopLeft: =60
        RadiusTopRight: =60
        Width: =91
        X: =37
        Y: =137
        ZIndex: =3

    Label1_15 As label:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =61
        LineHeight: =1.4
        Size: =18
        Text: =VarDadosUsuario.'Nome (Title)'
        Width: =479
        X: =161
        Y: =132
        ZIndex: =4

    Label1_16 As label:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.Lato
        Height: =50
        LineHeight: =1.4
        Text: =VarDadosUsuario.TipoUsuario
        Width: =479
        X: =161
        Y: =178
        ZIndex: =5

    Icon2_18 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =47
        Icon: =Icon.Cancel
        OnSelect: =Back(ScreenTransition.CoverRight)
        Width: =47
        X: =37
        Y: =40
        ZIndex: =6

    Button2_30 As button:
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(43, 43, 43, 1)
        FontWeight: =FontWeight.Semibold
        Height: =2
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(100, 118, 132, 1), -20%)
        RadiusBottomLeft: =20
        RadiusBottomRight: =20
        RadiusTopLeft: =20
        RadiusTopRight: =20
        Size: =24
        Text: =""
        Width: =640
        Y: =365
        ZIndex: =7

    Icon2_4 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =47
        Icon: =Icon.Person
        OnSelect: |-
            =Navigate('Tela Cadastro',ScreenTransition.Cover,{varAlterarDados:true})
        Width: =47
        X: =59
        Y: =293
        ZIndex: =8

    Label1_17 As label:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =61
        LineHeight: =1.4
        OnSelect: |-
            =Navigate('Tela Cadastro',ScreenTransition.Cover,{DadosUsuario:VarDadosUsuario,Edit:true})
        Size: =18
        Text: ="Meu Dados"
        Width: =479
        X: =128
        Y: =286
        ZIndex: =9

    Icon2_5 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =20
        Icon: =Icon.ChevronRight
        OnSelect: |-
            =Navigate('Tela Cadastro',ScreenTransition.Cover,{varAlterarDados:true})
        Width: =20
        X: =562
        Y: =306
        ZIndex: =10

    Button2_31 As button:
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(43, 43, 43, 1)
        FontWeight: =FontWeight.Semibold
        Height: =2
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(100, 118, 132, 1), -20%)
        RadiusBottomLeft: =20
        RadiusBottomRight: =20
        RadiusTopLeft: =20
        RadiusTopRight: =20
        Size: =24
        Text: =""
        Width: =640
        Y: =471
        ZIndex: =11

    Icon2_7 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =47
        Icon: =Icon.Tag
        Visible: =If(VarDadosUsuario.TipoUsuario = "Organizador",false,true)
        Width: =47
        X: =59
        Y: =399
        ZIndex: =12

    Label1_18 As label:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =104
        LineHeight: =1.4
        OnSelect: =Navigate('Meus Interesses', ScreenTransition.Cover)
        Size: =18
        Text: ="Interesses"
        Visible: =If(VarDadosUsuario.TipoUsuario = "Organizador",false,true)
        Width: =479
        X: =128
        Y: =367
        ZIndex: =13

    Icon2_8 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =20
        Icon: =Icon.ChevronRight
        Visible: =If(VarDadosUsuario.TipoUsuario = "Organizador",false,true)
        Width: =20
        X: =562
        Y: =415
        ZIndex: =14

    Button1_5 As button:
        BorderThickness: =0
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(64, 64, 64, 1)
        Fill: =RGBA(64, 64, 64, 1)
        FocusedBorderThickness: =0
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =79
        HoverFill: =RGBA(64, 64, 64, 1)
        OnSelect: =Exit()
        PressedColor: =RGBA(255, 255, 255, 1)
        PressedFill: =RGBA(64, 64, 64, 1)
        RadiusBottomLeft: =35
        RadiusBottomRight: =35
        RadiusTopLeft: =35
        RadiusTopRight: =35
        Size: =20
        Text: ="Sair do aplicativo"
        Width: =523
        X: =58
        Y: =1029
        ZIndex: =18

    Button2_32 As button:
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        DisabledFill: =RGBA(244, 244, 244, 1)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(43, 43, 43, 1)
        FontWeight: =FontWeight.Semibold
        Height: =2
        HoverColor: =RGBA(255, 255, 255, 1)
        HoverFill: =ColorFade(RGBA(100, 118, 132, 1), -20%)
        RadiusBottomLeft: =20
        RadiusBottomRight: =20
        RadiusTopLeft: =20
        RadiusTopRight: =20
        Size: =24
        Text: =""
        Visible: =If(VarDadosUsuario.TipoUsuario = "Organizador",false,true)
        Width: =640
        Y: =577
        ZIndex: =19

    Icon2_9 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =47
        Icon: =Icon.Help
        OnSelect: =Navigate('Tela Sobre',ScreenTransition.Cover)
        Width: =47
        X: =59
        Y: =If(VarDadosUsuario.TipoUsuario = "Organizador",399,505)
        ZIndex: =20

    Label1_19 As label:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledColor: =RGBA(166, 166, 166, 1)
        Font: =Font.Lato
        FontWeight: =FontWeight.Bold
        Height: =104
        LineHeight: =1.4
        OnSelect: =Navigate('Tela Sobre',ScreenTransition.Cover)
        Size: =18
        Text: ="Sobre"
        Width: =479
        X: =128
        Y: =If(VarDadosUsuario.TipoUsuario = "Organizador",367,473)
        ZIndex: =21

    Icon2_10 As icon.Reset:
        BorderColor: =RGBA(197, 203, 207, 1)
        Color: =RGBA(255, 255, 255, 1)
        DisabledBorderColor: =RGBA(166, 166, 166, 1)
        DisabledColor: =RGBA(244, 244, 244, 1)
        Height: =20
        Icon: =Icon.ChevronRight
        OnSelect: =Navigate('Tela Sobre',ScreenTransition.Cover)
        Width: =20
        X: =562
        Y: =If(VarDadosUsuario.TipoUsuario = "Organizador",415,521)
        ZIndex: =22

